name: run docker action
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run docker action
        id: docker-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@maroctamorg'

      - name: output
        run:  echo "${{ steps.docker-action.outputs.time }}"
        
